"""
Notebook rendering orchestration.

This module is responsible for walking through the cells
of a Jupyter notebook and sending each cell to the
appropriate renderer.

It does NOT:

- parse Markdown
- render individual Markdown elements
- render individual code elements
- configure the PDF document
- create ReportLab styles
"""

from .markdown import add_markdown
from .code import (
    add_code_cell,
    add_cell_outputs,
)


class NotebookRenderer:
    """
    Coordinates the rendering of Jupyter notebook cells.

    This class acts as the bridge between the notebook
    structure and the individual cell renderers.
    """

    def __init__(
        self,
        styles,
        notebook_language,
        notebook_dir
    ):
        """
        Store the information required by the renderers.

        Parameters
        ----------
        styles:
            ReportLab styles used throughout the PDF.

        notebook_language:
            Programming language associated with the notebook.

        notebook_dir:
            Directory containing the notebook. This is useful
            when resolving local images and other resources.
        """

        self.styles = styles

        self.notebook_language = notebook_language

        self.notebook_dir = notebook_dir


    def render(
        self,
        notebook,
        content
    ):
        """
        Render every cell in the notebook.

        Markdown cells are sent to the Markdown renderer.

        Code cells are sent to the code renderer, followed
        by rendering any outputs produced by that cell.
        """

        for cell in notebook.cells:

            # Get the cell source.
            source = cell.get(
                "source",
                ""
            )

            # Jupyter may store source as a list of strings.
            # Convert it into one continuous string.
            if isinstance(source, list):

                source = "".join(source)

            # Ignore completely empty cells.
            if not source:

                continue

            # Determine what kind of notebook cell this is.
            cell_type = cell.get(
                "cell_type"
            )

            # ---------------------------------------------
            # Markdown cell
            # ---------------------------------------------

            if cell_type == "markdown":

                self._render_markdown(
                    content,
                    source,
                    cell,
                )

            # ---------------------------------------------
            # Code cell
            # ---------------------------------------------

            elif cell_type == "code":

                self._render_code(
                    content,
                    source,
                    cell,
                )


    def _render_markdown(
        self,
        content,
        source,
        cell
    ):
        """
        Render a Markdown notebook cell.

        Notebook-specific information such as attachments
        is passed along to the Markdown renderer.
        """

        add_markdown(
            content,
            source,
            self.styles,
            cell.get(
                "attachments",
                {}
            ),
            cell,
            self.notebook_dir,
        )


    def _render_code(
        self,
        content,
        source,
        cell
    ):
        """
        Render a code notebook cell and its outputs.

        The code itself and its outputs are handled by
        the code rendering module.
        """

        # Render the actual source code.
        add_code_cell(
            content,
            source,
            self.styles,
            self.notebook_language,
        )

        # Render outputs generated by the code cell.
        add_cell_outputs(
            content,
            cell,
        )